# Generated by Django 5.1.6 on 2025-05-28 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0014_remove_worksession_task_price_at_creation'),
    ]

    operations = [
    ]
