services:
  - type: web
    name: trabalhadores
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn teachers.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "trabalhadores.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://trabalhadores.onrender.com"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
    plan: free
    autoDeploy: true
    numInstances: 1
