services:
  - type: web
    name: trabalhadores
    env: python
    buildCommand: chmod +x .render-build.sh && ./.render-build.sh
    startCommand: gunicorn teachers.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "trabalhadores.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://trabalhadores.onrender.com"
      # Database configuration
      - key: DATABASE_URL
        value: ""
      # Superuser configuration
      - key: SUPERUSER_USERNAME
        value: "admin"
      - key: SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: SUPERUSER_PASSWORD
        generateValue: true
    plan: free
    autoDeploy: true
    numInstances: 1
