name: Update Documentation

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate Documentation
        run: |
          # Add your documentation generation commands here
          python manage.py generate_docs
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Add all documentation files
          git add docs/ README.md
          
          # Only commit if there are changes
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "docs: update documentation"
            git push origin main
          fi