name: Update Documentation

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get full history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Debug Python Environment
        run: |
          echo "=== Python Version ==="
          python --version
          echo "=== Python Path ==="
          which python
          echo "=== Python Location ==="
          which python3
          echo "=== Python Environment ==="
          python -c "import sys; print(sys.executable)"
          echo "=== Python Modules Path ==="
          python -c "import sys; print(sys.path)"

      - name: Install dependencies
        run: |
          echo "=== Current Directory ==="
          pwd
          echo "=== Directory Contents ==="
          ls -la
          
          echo "=== Installing pip ==="
          python -m pip install --upgrade pip
          pip --version
          
          echo "=== Installing requirements ==="
          pip install -r requirements.txt
          
          echo "=== Installed Packages ==="
          pip list
          
          echo "=== Django Version ==="
          python -c "import django; print(django.get_version())"

      - name: Generate Documentation
        run: |
          echo "=== Current Directory ==="
          pwd
          echo "=== Directory Contents ==="
          ls -la
          
          echo "=== Python Path ==="
          python -c "import sys; print(sys.path)"
          
          echo "=== Starting documentation generation..."
          python manage.py generate_docs
          echo "=== Documentation generation complete ==="
          
          echo "=== Directory Contents After Generation ==="
          ls -la
          
          echo "=== Documentation Files ==="
          find . -name "*.md" -type f -exec ls -l {} \;

      - name: Debug output
        if: always()
        run: |
          echo "=== Workflow Status ==="
          echo "Status: ${{ job.status }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"
          
          echo "=== Git Status ==="
          git status
          
          echo "=== Git Remote ==="
          git remote -v
          
          echo "=== Git Config ==="
          git config --list